"""Общий контракт медиадвижка (Qt Multimedia / VLC)."""

from __future__ import annotations

from typing import Callable, Protocol


class MediaEngine(Protocol):
    """Минимальный API для Player: локальные файлы и http(s) URL."""

    def play_media(self, source: str) -> None: ...

    def pause_media(self) -> None: ...

    def resume_media(self) -> None: ...

    def stop_media(self) -> None: ...

    def is_playing(self) -> bool: ...

    def get_position_ms(self) -> int: ...

    def set_position_ms(self, ms: int) -> None: ...

    def request_seek(self, ms: int) -> None: ...

    def get_duration_ms(self) -> int: ...

    def get_volume(self) -> int: ...

    def set_volume(self, value: int) -> None: ...

    def get_duck_gain(self) -> float: ...

    def set_duck_gain(self, gain: float) -> None: ...

    def on_playing(self, callback: Callable[[], None]) -> None: ...

    def on_paused(self, callback: Callable[[], None]) -> None: ...

    def on_stopped(self, callback: Callable[[], None]) -> None: ...

    def on_ended(self, callback: Callable[[], None]) -> None: ...

    def on_error(self, callback: Callable[[str], None]) -> None: ...
