"""Сохранение токенов и cookies.

Yandex OAuth — в системном keyring (короткий секрет).
YouTube cookies — в локальный файл: Windows CredWrite не принимает
большие blob'ы (ошибка 1783).

Для YouTube Music (ytmusicapi) нужен не «просто список кук», а auth JSON
с request headers. Quantis умеет сконвертировать типичные экспорты
(Cookie-Editor JSON, Netscape, сырые headers из DevTools).
"""

from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path

from keyring import delete_password, get_password, set_password
from keyring.errors import KeyringError, PasswordDeleteError

from quantis.config.clients import Clients
from quantis.config.constants import (
    SERVICE_NAME_YANDEX,
    SERVICE_NAME_YOUTUBE_COOKIE,
    USER,
)
from quantis.utils import app_paths

logger = logging.getLogger(__name__)

_YTM_ORIGIN = "https://music.youtube.com"
_COOKIE_NAME_RE = re.compile(r"^[A-Za-z0-9_.\-]+$")
_MAX_SECRET_BYTES = 1_048_576


def _chmod_private(path: Path, mode: int = 0o600) -> None:
    try:
        os.chmod(path, mode)
    except OSError:
        pass


def _write_private_text(path: Path, text: str) -> None:
    """Пишет секрет в файл с правами 0o600 (на POSIX)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = text.encode("utf-8")
    if len(encoded) > _MAX_SECRET_BYTES:
        raise ValueError("Файл cookies слишком большой")
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(path, flags, 0o600)
    try:
        os.write(fd, encoded)
    finally:
        os.close(fd)
    _chmod_private(path)


def _read_text_limited(path: Path, limit: int = _MAX_SECRET_BYTES) -> str:
    data = path.read_bytes()
    if len(data) > limit:
        raise ValueError("Файл cookies слишком большой")
    return data.decode("utf-8")


def _youtube_cookie_path() -> Path:
    return app_paths.credentials_dir() / "youtube_cookies.txt"


def youtube_netscape_cookies_path() -> Path:
    """Netscape cookies для yt-dlp (отдельно от auth JSON ytmusicapi)."""
    return app_paths.credentials_dir() / "youtube_cookies.netscape"


def _cookie_header_from_auth_json(text: str) -> str | None:
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return None
    if not isinstance(parsed, dict):
        return None
    for key, value in parsed.items():
        if str(key).lower() == "cookie":
            return str(value)
    return None


def _write_netscape_cookies(cookie_header: str, dest: Path | None = None) -> Path:
    """Пишет Netscape HTTP Cookie File для yt-dlp из Cookie header."""
    dest = dest or youtube_netscape_cookies_path()
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Quantis for yt-dlp",
        "# https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp",
    ]
    # session cookies: expires=0
    for part in cookie_header.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name or not _COOKIE_NAME_RE.match(name):
            continue
        # domain, include_subdomains, path, secure, expires, name, value
        secure = (
            "TRUE"
            if name.startswith("__Secure-") or name.startswith("__Host-")
            else "FALSE"
        )
        lines.append(f".youtube.com\tTRUE\t/\t{secure}\t0\t{name}\t{value}")
    _write_private_text(dest, "\n".join(lines) + "\n")
    return dest


def ensure_youtube_netscape_cookies() -> Path | None:
    """Гарантирует Netscape-файл для yt-dlp из сохранённого auth JSON.

    Returns:
        Путь к файлу или None, если кук нет.
    """
    netscape = youtube_netscape_cookies_path()
    auth_path = _youtube_cookie_path()
    if not auth_path.is_file():
        return netscape if netscape.is_file() else None

    try:
        auth_text = _read_text_limited(auth_path).strip()
        _chmod_private(auth_path)
    except OSError:
        logger.exception("Не удалось прочитать auth cookies")
        return netscape if netscape.is_file() else None
    except ValueError:
        logger.warning("Auth cookies слишком большие, пропускаем")
        return netscape if netscape.is_file() else None

    cookie_header = _cookie_header_from_auth_json(auth_text)
    if not cookie_header:
        return netscape if netscape.is_file() else None

    # Пересобираем, если auth новее netscape или netscape нет
    try:
        need_write = (
            not netscape.is_file()
            or auth_path.stat().st_mtime > netscape.stat().st_mtime
        )
    except OSError:
        need_write = True
    if need_write:
        try:
            _write_netscape_cookies(cookie_header, netscape)
        except OSError:
            logger.exception("Не удалось записать Netscape cookies для yt-dlp")
            return None
    if netscape.is_file():
        _chmod_private(netscape)
        return netscape
    return None


def youtube_yt_dlp_cookiefile() -> str | None:
    """Путь к cookiefile для YoutubeDL, либо None."""
    path = ensure_youtube_netscape_cookies()
    return str(path) if path is not None else None


def _cookie_header_from_items(items: list[dict]) -> str:
    """Собирает Cookie header из Cookie-Editor / EditThisCookie JSON."""
    pairs: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "").strip()
        if not name or not _COOKIE_NAME_RE.match(name):
            continue
        domain = str(item.get("domain") or "").lower()
        # Берём youtube / google куки; пустой domain тоже ок
        if domain and ("youtube" not in domain and "google" not in domain):
            continue
        value = str(item.get("value") or "")
        pairs.append(f"{name}={value}")
    if not pairs:
        raise ValueError(
            "В JSON-массиве кук не нашлось cookies для youtube/google. "
            "Экспортируйте куки с music.youtube.com или youtube.com."
        )
    return "; ".join(pairs)


def _cookie_header_from_netscape(text: str) -> str:
    pairs: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            # иногда пробелы вместо табов
            parts = re.split(r"\s+", line)
        if len(parts) < 7:
            continue
        domain, _flag, _path, _secure, _expires, name, value = parts[:7]
        domain_l = domain.lower()
        if "youtube" not in domain_l and "google" not in domain_l:
            continue
        if not _COOKIE_NAME_RE.match(name):
            continue
        pairs.append(f"{name}={value}")
    if not pairs:
        raise ValueError("Netscape cookies.txt не содержит youtube/google кук")
    return "; ".join(pairs)


def _looks_like_cookie_header(text: str) -> bool:
    if "=" not in text or "\n" in text.strip():
        return False
    # name=value; name2=value2
    parts = [p.strip() for p in text.split(";") if p.strip()]
    if len(parts) < 2:
        return False
    return all(
        "=" in p and _COOKIE_NAME_RE.match(p.split("=", 1)[0].strip())
        for p in parts[:5]
    )


def _looks_like_raw_headers(text: str) -> bool:
    lower = text.lower()
    return ("cookie:" in lower or "cookie :" in lower) and (
        "\n" in text or "authorization:" in lower or "x-goog-authuser:" in lower
    )


def _auth_json_from_cookie_header(cookie_header: str) -> str:
    """Собирает browser.json для ytmusicapi из Cookie header."""
    from ytmusicapi.helpers import (
        get_authorization,
        initialize_headers,
        sapisid_from_cookie,
    )

    has_secure = "__Secure-3PAPISID=" in cookie_header
    has_sapisid = re.search(r"(?:^|;\s*)SAPISID=", cookie_header) is not None
    if not has_secure and not has_sapisid:
        raise ValueError(
            "В куках нет SAPISID / __Secure-3PAPISID — вы не залогинены на "
            "music.youtube.com. Откройте music.youtube.com в браузере и "
            "экспортируйте куки снова."
        )

    # ytmusicapi читает именно __Secure-3PAPISID
    if not has_secure and has_sapisid:
        match = re.search(r"(?:^|;\s*)SAPISID=([^;]+)", cookie_header)
        if match:
            cookie_header = (
                cookie_header.rstrip("; ")
                + f"; __Secure-3PAPISID={match.group(1).strip()}"
            )

    try:
        sapisid = sapisid_from_cookie(cookie_header)
    except Exception as exc:
        match = re.search(
            r"(?:^|;\s*)(?:__Secure-3PAPISID|SAPISID)=([^;]+)", cookie_header
        )
        if not match:
            raise ValueError(
                "Не удалось прочитать SAPISID из кук. "
                "Скопируйте Request Headers с music.youtube.com (см. подсказку)."
            ) from exc
        sapisid = match.group(1).strip()

    headers = dict(initialize_headers())
    headers["Cookie"] = cookie_header
    headers["x-origin"] = _YTM_ORIGIN
    headers["X-Goog-AuthUser"] = "0"
    # Нужен для AuthType.BROWSER
    headers["Authorization"] = get_authorization(f"{sapisid} {_YTM_ORIGIN}")
    return json.dumps(headers, ensure_ascii=False, indent=2)


def _normalize_youtube_auth(value: str) -> str:
    """Приводит ввод пользователя к JSON headers для YTMusic(auth=...)."""
    text = value.strip()
    if not text:
        raise ValueError("Cookie не может быть пустым")

    # Путь к уже готовому auth-файлу
    path = Path(text)
    if path.is_file():
        return text

    # 1) Сырые Request Headers из DevTools → ytmusicapi.setup
    if _looks_like_raw_headers(text):
        try:
            from ytmusicapi import setup

            return setup(headers_raw=text)
        except Exception as exc:
            raise ValueError(
                "Не удалось разобрать Request Headers. "
                "Скопируйте headers целиком с POST browse на music.youtube.com "
                f"(нужны cookie и x-goog-authuser). Детали: {exc}"
            ) from exc

    # 2) JSON
    if text.startswith("{") or text.startswith("["):
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError as exc:
            raise ValueError(
                "Невалидный JSON. Вставьте Request Headers, Cookie-Editor JSON "
                "или готовый browser.json от ytmusicapi."
            ) from exc

        if isinstance(parsed, list):
            cookie_header = _cookie_header_from_items(parsed)
            return _auth_json_from_cookie_header(cookie_header)

        if isinstance(parsed, dict):
            # Уже headers-объект
            lower_keys = {str(k).lower() for k in parsed}
            if "cookie" in lower_keys or "authorization" in lower_keys:
                # Дополняем недостающее
                cookie_val = None
                for k, v in parsed.items():
                    if str(k).lower() == "cookie":
                        cookie_val = str(v)
                        break
                if cookie_val and "authorization" not in lower_keys:
                    return _auth_json_from_cookie_header(cookie_val)
                # Нормализуем через dumps
                return json.dumps(parsed, ensure_ascii=False, indent=2)

            # Иногда кладут {"cookies": [...]}
            if "cookies" in parsed and isinstance(parsed["cookies"], list):
                cookie_header = _cookie_header_from_items(parsed["cookies"])
                return _auth_json_from_cookie_header(cookie_header)

            raise ValueError(
                "JSON-объект не похож на headers ytmusicapi. "
                "Нужны поля Cookie / Authorization, либо массив кук Cookie-Editor."
            )

        raise ValueError("Auth должен быть JSON-объектом (headers) или массивом кук")

    # 3) Netscape cookies.txt
    if "# Netscape" in text or ("TRUE" in text and "\t" in text):
        cookie_header = _cookie_header_from_netscape(text)
        return _auth_json_from_cookie_header(cookie_header)

    # 4) Готовая строка Cookie: a=b; c=d
    if _looks_like_cookie_header(text):
        return _auth_json_from_cookie_header(text)

    raise ValueError(
        "Непонятный формат. Нужно одно из:\n"
        "• Request Headers с music.youtube.com (DevTools → Network → browse → Headers)\n"
        "• JSON Cookie-Editor / EditThisCookie с youtube.com\n"
        "• Готовый browser.json от ytmusicapi browser"
    )


def _validate_youtube_auth(value: str) -> str:
    """Проверяет/нормализует auth для ytmusicapi."""
    return _normalize_youtube_auth(value)


def yandex_token() -> str:
    return get_password(SERVICE_NAME_YANDEX, USER) or ""


def yotube_cookie() -> str:
    path = _youtube_cookie_path()
    if path.is_file():
        try:
            text = _read_text_limited(path).strip()
            _chmod_private(path)
            return text
        except ValueError:
            logger.warning("YouTube cookies слишком большие: %s", path)
            return ""
        except OSError:
            logger.exception("Не удалось прочитать YouTube cookies из %s", path)
    try:
        legacy = get_password(SERVICE_NAME_YOUTUBE_COOKIE, USER) or ""
    except KeyringError:
        legacy = ""
    if legacy:
        try:
            _write_private_text(path, legacy)
            try:
                delete_password(SERVICE_NAME_YOUTUBE_COOKIE, USER)
            except (KeyringError, PasswordDeleteError):
                pass
        except OSError:
            logger.exception("Не удалось мигрировать YouTube cookies в файл")
        return legacy
    return ""


def youtube_cookie() -> str:
    """Алиас без опечатки для yotube_cookie()."""
    return yotube_cookie()


def save_yandex_token(token: str) -> None:
    value = token.strip()
    if not value:
        raise ValueError("Токен не может быть пустым")
    set_password(SERVICE_NAME_YANDEX, USER, value)
    Clients().reload_yandex_client()


def delete_yandex_token() -> None:
    """Удаляет локальный OAuth-токен из keyring. Сам Яндекс его не отзывает."""
    try:
        delete_password(SERVICE_NAME_YANDEX, USER)
    except PasswordDeleteError:
        pass
    except KeyringError as exc:
        raise RuntimeError(f"Не удалось удалить токен: {exc}") from exc
    Clients().reload_yandex_client()


def save_youtube_cookie(cookie: str) -> None:
    value = _validate_youtube_auth(cookie)
    # Если вернули путь к существующему файлу — копируем содержимое к нам
    path = _youtube_cookie_path()
    as_path = Path(value)
    if as_path.is_file() and as_path.resolve() != path.resolve():
        try:
            value = _read_text_limited(as_path)
        except ValueError as exc:
            raise ValueError(str(exc)) from exc
        value = _normalize_youtube_auth(value)
    try:
        _write_private_text(path, value)
    except ValueError:
        raise
    except OSError as exc:
        raise RuntimeError(f"Не удалось сохранить cookies: {exc}") from exc

    cookie_header = _cookie_header_from_auth_json(value)
    if cookie_header:
        try:
            _write_netscape_cookies(cookie_header)
        except OSError:
            logger.exception("Не удалось экспортировать Netscape cookies для yt-dlp")

    try:
        delete_password(SERVICE_NAME_YOUTUBE_COOKIE, USER)
    except (KeyringError, PasswordDeleteError):
        pass
    Clients().reload_youtube_client()
